/*
 * Copyright (c) 2019-2026 Airbus Commercial Aircraft
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * As an additional exemption you are allowed to compile & link against the
 * OpenSSL libraries as published by the OpenSSL project. See the file
 * COPYING for details.
 *
 */


/* ---------------------------------------------------------------------
 * Crash Recovery - logger main
 *
 * Reads in existing unencrypted (plain) log file and converts it according BN19
 *
 * [BN19] Erik-Oliver Blass and Guevara Noubir.
 * Forward Integrity and Crash Recovery for Secure Logs. Cryptology ePrint Archive, Paper 2019/506. 2019.
 * url: https://eprint.iacr.org/2019/506.
 *
 * This implementation was ported from Florian Hördt's master thesis example C++ code into C.
 * https://github.com/Genfood/secure-logging-cr
 *
 * NOTE: The count of lines in the file given must be at least 5 (THE_K)
 * The input file is line-oriented. The line length must not exceed 2048 bytes.
 * UTF-8 is supported. 2048 octes does not mean 2048 characters or symbols.
 * Each UTF-8 symbol might  be 4 bytes long.
 *
 * Currently the key (master key) is generated by this logger, when
 * there is none. Existing session key is deleted!
 * The master key then is used later by the verifier.
 *
 * Arguments
 * --key, -k:     Full file name (path) of initial key
 * --in, -i:      Full file name (path) of the line-oriented input plain text file
 * --out, -o:     Full file name (path) of the encrypted output file
 * --maxlogs, -m: Number of log lines the original plain log file provides
 *
 * Returns 0 on SUCCESS and non-zero on FAILURE (main logic)
 */


#include <stdio.h>
#include <locale.h>
#include <sys/types.h>
#include <string.h>
#include <stdlib.h>
#include <glib.h>
#include <math.h> //-- ceil 
#include <openssl/rand.h>
#include <openssl/evp.h>
#include <openssl/sha.h>

#include "utils_slog.h"
#include "cr_crypto.h"
#include "cr_pi_shared.h"
#include "cr_pi_logger_context.h"
#include "cr_pi_logger.h"
#include "messages.h"

#define MAX_LINE_LENGTH MESSAGE_LEN_SLOGCR /* octet length of the define max log length (this is NOT the number of characters or symbols) */

//----------------------------------------------------------------------
// main
//
// returns 0 only in case of success (main logic).

int main(int argc, char *argv[])
{
  setlocale(LC_ALL, "");
  gboolean is_arg_key = FALSE;
  gboolean is_arg_in = FALSE;
  gboolean is_arg_out = FALSE;
  gboolean is_arg_maxlogs = FALSE;

  if (1 > argc)
    {
      // fixed: msg_error
      msg_error("Wrong count of arguments");
      return 1; //-- ERROR
    }

  GOptionEntry entries[] =
  {
    { "key", 'k', 0, G_OPTION_ARG_NONE, &is_arg_key, "Full file name (path) of the master key", NULL },
    { "in", 'i', 0, G_OPTION_ARG_NONE, &is_arg_in, "Full file name (path) of the line-oriented input plain text file", NULL }, //-- first param of readLogs
    { "out", 'o', 0, G_OPTION_ARG_NONE, &is_arg_out, "Full file name (path) of the encrypted output file", NULL }, //-- 4th param of CreatePIContext, used as filename without extension
    { "maxlogs", 'm', 0, G_OPTION_ARG_NONE, &is_arg_maxlogs, "Number of log lines the original plain log file provides", NULL }, //-- maxlines to be read
    { 0 }
  };

  GError *error = NULL;
  GOptionContext *context;

  context = g_option_context_new ("- logger (Crash Recovery)");
  g_option_context_add_main_entries(context, entries, NULL);
  if (!g_option_context_parse(context, &argc, &argv, &error))
    {
      // If parsing failed, print the error and exit.
      // fixed: msg_error
      msg_error("Failed to parse command-line options",
              evt_tag_str("error", error->message));
      g_error_free(error);
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  if ((5 != argc) && (FALSE == is_arg_key) && (FALSE == is_arg_in) && (FALSE == is_arg_out)
      && (FALSE == is_arg_maxlogs))
    {
      // fixed: msg_error
      msg_error("Wrong count of arguments");
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  //-- check master key, --key, -k
  char szMasterKeyPath[PATH_MAX];
  g_strlcpy(szMasterKeyPath, argv[1], PATH_MAX);
  if ( ! g_file_test(szMasterKeyPath, G_FILE_TEST_IS_REGULAR))
    {
      // fixed: msg_error
      msg_error("Invalid master key file", 
                evt_tag_str("path", szMasterKeyPath));
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  //-- check logs, --in, -i
  // InputFileName: plain test log file to read
  char szInputFileName[PATH_MAX];
  g_strlcpy(szInputFileName, argv[2], PATH_MAX);
  if ( ! g_file_test(szInputFileName, G_FILE_TEST_IS_REGULAR))
    {
      // fixed: msg_error
      msg_error("Invalid input log file", 
                evt_tag_str("path", szInputFileName));
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  //-- check output filename, --out, -o
  // OutputFileName: encrypted log file to write
  char szOutputFileName[PATH_MAX];
  char szOutputDir[PATH_MAX];
  g_strlcpy(szOutputFileName, argv[3], PATH_MAX);
  gboolean is_valid_dir_from_file = get_path_from_file(szOutputFileName, szOutputDir, sizeof(szOutputDir));
  if (FALSE == is_valid_dir_from_file)
    {
      // fixed: msg_error
      msg_error("Invalid output file path", 
                evt_tag_str("path", szOutputFileName));
      g_option_context_free(context);
      return 1; //-- ERROR   (alternative: mkdir -p ...)
    }

  size_t dir_len = strlen(szOutputDir);
  if (dir_len >= 0 && szOutputDir[dir_len - 1] != '/')
    {
      g_strlcat(szOutputDir, "/", PATH_MAX);
    }

  //-- check maxlogs
  int maxlogs;
  gchar *endptr;
  long int litemp = strtol(argv[4], &endptr, 10);
  if (*endptr != '\0')
    {
      // fixed: msg_error
      msg_error("Invalid maxlogs value", 
                evt_tag_str("value", argv[4]));
      g_option_context_free(context);
      return 1; //-- ERROR
    }
  if (litemp > INT_MAX)
    {
      // fixed: msg_error
      msg_error("maxlogs exceeds INT_MAX", 
                evt_tag_str("value", argv[4]));
      g_option_context_free(context);
      return 1; //-- ERROR
    }
  maxlogs = (int) litemp;
  if (maxlogs <= THE_K) //-- endless loop protection when filling Random buffer
    {
      //-- anyhow, maxlogs should be at least 4096 to be reliable ensure Crash Recovery,
      //   see https://eprint.iacr.org/2019/506.pdf, p 22, fig 3
      // fixed: msg_error
      msg_error("maxlogs is out of range", 
                evt_tag_printf("maxlogs", "%d", maxlogs), 
                evt_tag_printf("minimum", "%d", THE_K + 1));
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  msg_info("key (initial key)", evt_tag_str("path", argv[1]));
  msg_info("in (plain log file)", evt_tag_str("path", argv[2]));
  msg_info("out (enc log file)", evt_tag_str("path", argv[3]));
  msg_info("maxlogs (count of log lines)", evt_tag_printf("value", "%s", argv[4]));

  g_option_context_free(context);

  msg_info("szMasterKeyPath", evt_tag_str("path", szMasterKeyPath));
  msg_info("szInputFileName", evt_tag_str("path", szInputFileName));
  msg_info("szOutputFileName", evt_tag_str("path", szOutputFileName));
  msg_info("szOutputDir", evt_tag_str("path", szOutputDir)); //-- derived from szOutputFileName. Will NOT be created. Must exist.
  msg_info("maxlogs", evt_tag_printf("value", "%d", maxlogs));

  cr_pi_logger_context loggerCtx = {NULL, NULL, NULL, NULL, INT_MAX};

  loggerCtx.p_MasterKeyPath = szMasterKeyPath;
  loggerCtx.p_OutputDirectoryPath = szOutputDir;
  loggerCtx.p_InputPlainLogPath = szInputFileName;
  loggerCtx.p_OutputEncLogPath = szOutputFileName;
  loggerCtx.maxLogs = maxlogs;

  //-- READ plain log file ---

  // read the logs from the provided log file.
  // char **logs = cr_pi_logger_main_readLogs(loggerCtx.logPath, &logCount, loggerCtx.maxLogs);
  char szBuffer[256];
  memset(szBuffer, 0, sizeof(szBuffer));
  get_human_timestamp(szBuffer);
  msg_info("timestamp", evt_tag_str("time", szBuffer));
  struct timespec start, end;
  start = get_ts_now();
  error = NULL;
  GPtrArray *gpa_logs = cr_pi_logger_main_read_logs_glib(loggerCtx.p_InputPlainLogPath, loggerCtx.maxLogs, &error);
  if (error)
    {
      // fixed: msg_error
      msg_error("Failed to read log file", 
                evt_tag_str("error", error->message)); 
        
      g_error_free(error);
      return 1; //-- ERROR
    }
  if (NULL == gpa_logs)
    {
      // fixed: msg_error
      msg_error("cr_logger: Failed to read log file! (NULL == gpa_logs)");
      return 1; //-- ERROR
    }
  //-- log file read. Lines as GString*'s in gap_logs.

  // Create a Logger Context struct, which contains all important information, like the maxmum number of log files.
  cr_PIContext *ctx = cr_CreatePIContext(gpa_logs->len, TRUE, loggerCtx.p_MasterKeyPath, loggerCtx.p_OutputDirectoryPath,
                                         loggerCtx.p_OutputEncLogPath);
  if (NULL == ctx)
    {
      return 1; //-- ERROR
    }
  // Call the init algorithm.
  // This will initialize the log file of the according size, and will write the pseudo random pad.
  if (FALSE == cr_Init(ctx) )
    {
      // fixed: msg_error
      msg_error("cr_logger: cr_Init, Initialization failed");
      g_free(ctx->keyPath);
      g_free(ctx);
      g_ptr_array_free(gpa_logs, TRUE);
      return 1; //-- ERROR
    }

  gboolean is_add = FALSE;
  msg_info("gpa_logs->len", evt_tag_printf("len", "%u", gpa_logs->len));
  for (guint i = 0; i < gpa_logs->len; ++i)
    {
      // Pass the modified string to AddLogEntry (add item).
      GString *line = (GString *) g_ptr_array_index(gpa_logs, i);
      if (line->len > MAX_LINE_LENGTH)
        {
          // fixed: msg_warning
          msg_warning("Log string is too long and will be shortened", 
                      evt_tag_printf("line", "%u", i), 
                      evt_tag_printf("length", "%zu", line->len), 
                      evt_tag_printf("max_length", "%d", MAX_LINE_LENGTH));

          msg_info("Before truncate", evt_tag_str("line", line->str));
          truncate_utf8_gstring(line, MAX_LINE_LENGTH);
          msg_info("After truncate", evt_tag_str("line", line->str));
        }
      if ( (0 == (i & 511)) || (i == (gpa_logs->len - 1)))
        {
          msg_info("process line", evt_tag_printf("current", "%u", i + 1), evt_tag_printf("total", "%u", gpa_logs->len));
        }
      is_add = cr_AddLogEntry(ctx, (unsigned char *)(line->str), line->len); //-- line->len: count of octets
      if (FALSE == is_add)
        {
          // fixed: msg_warning
          msg_error("Failed to add log entry", 
                    evt_tag_printf("line", "%u", i));
          break; //-- ERROR, Note: Cancel on first error
        }

    } //-- for gpa_logs->len


  if (TRUE == is_add)
    {
      msg_info("cr_logger: Logs have been written successfully", evt_tag_printf("count", "%u", gpa_logs->len));
    }
  else
    {
      msg_info("cr_logger: Logs have NOT been written successfully", evt_tag_printf("count", "%u", gpa_logs->len));
    }


  //-- clean up
  if (ctx->logFile)
    {
      fclose(ctx->logFile);
      ctx->logFile = NULL;
    }
  if (ctx->keyFile)
    {
      fclose(ctx->keyFile);
      ctx->keyFile = NULL;
    }
  g_free(ctx->keyPath);
  ctx->keyPath = NULL;
  g_free(ctx);
  ctx = NULL;
  g_ptr_array_free(gpa_logs, TRUE);

  end = get_ts_now();
  (void) get_time_diff_in_milliseconds(start, end, "Crash Recovery Logger (read + encrypt)");
  msg_info("");
  memset(szBuffer, 0, sizeof(szBuffer));
  get_human_timestamp(szBuffer);
  msg_info("timestamp", evt_tag_str("time", szBuffer));

  //-- return value main logic
  if (FALSE == is_add)
    {
      return 1; //-- ERROR, main logic
    }
  return 0; //-- SUCCESS
}